services:
  - type: web
    name: barcode-processor
    env: ruby
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: ". $HOME/.bashrc && rbenv local 2.6.6 && ruby -v && bundle exec rails s -p $PORT -e production"
    packages:
      - zbar-tools 
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barcode_processor_db
          property: connectionString

databases:
  - name: barcode_processor_db
    databaseName: barcode_processor
    user: barcode_processor