services:
  - type: web
    name: barcode-processor
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: barcode_processor_db
          property: connectionString

databases:
  - name: barcode_processor_db
    databaseName: barcode_processor
    user: barcode_processor